name: test

on:
  pull_request: {}
  push:
    branches:
      - "**"

jobs:
  test:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@0.30.2
    needs: prepare-secrets
    with:
      install-go: true
      go-version: "1.19.4"
      install-goreleaser: true
      install-cosign: true
      install-syft: true
      build-commands: make build
      test-commands: |
        DATE="$(date +%Y%m%d%H%M%S)"
        docker build --build-arg date=${DATE} -t ttl.sh/sbom-operator-oci-test-${DATE}:1h internal/target/oci/fixtures
        docker push ttl.sh/sbom-operator-oci-test-${DATE}:1h
        DIGEST=$(docker inspect ttl.sh/sbom-operator-oci-test-${DATE}:1h --format='{{index .RepoDigests 0}}')
        syft registry:${DIGEST} -o json > internal/target/oci/fixtures/sbom.json

        TEST_DIGEST="${DIGEST}" go test $(go list ./...) -coverprofile cover.out
        COSIGN_REPOSITORY="ttl.sh/sbom-operator-oci-test-${DATE}" cosign download sbom ${DIGEST}
      report-coverage: true
      coverage-file: cover.out
      build-image: true
      docker-tag: ghcr.io/ckotzbauer/sbom-operator:latest
      scan-image: true
