name: test

on:
  pull_request: {}
  push:
    branches:
      - "**"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.2'

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: "v1.7.0"
          install-only: true

      - name: Build binary
        run: make build

      - name: Unit tests
        env:
          REGISTRY_USER: ckotzbauer
          REGISTRY_TOKEN: ${{ secrets.GHCR_PASSWORD }}
        run: |
          make test

          DATE="$(date +%Y%m%d%H%M%S)"

          docker login -u "$REGISTRY_USER" -p "$REGISTRY_TOKEN" ghcr.io
          docker build --build-arg date=${DATE} -t ghcr.io/ckotzbauer/sbom-operator/oci-test:${DATE} internal/target/oci/fixtures
          docker push ghcr.io/ckotzbauer/sbom-operator/oci-test:${DATE}
          DIGEST=$(docker inspect ghcr.io/ckotzbauer/sbom-operator/oci-test:${DATE} --format='{{index .RepoDigests 0}}')

          syft registry:${DIGEST} -o json > internal/target/oci/fixtures/sbom.json
          TEST_DIGEST="${DIGEST}" go test $(go list ./...) -coverprofile cover.out

          COSIGN_REPOSITORY="ghcr.io/ckotzbauer/sbom-operator/oci-test" cosign download sbom ${DIGEST}

      - uses: codecov/codecov-action@v3
        with:
          files: cover.out

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          load: true
          platforms: linux/amd64
          tags: |
            ghcr.io/ckotzbauer/sbom-operator:latest

      - name: Container scan
        uses: ckotzbauer/actions-toolkit/grype@0.15.0
        with:
          scan-target: ghcr.io/ckotzbauer/sbom-operator
          fail-on: "medium"
          config-file: ".github/grype.yaml"
